apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-spring-testing
spec:
  title: Spring Testing
  description: Play area for testing Spring.
  url: https://github.com/eduk8s-tests/lab-spring-testing
  vendor: eduk8s.io
  duration: 60m
  content: 
    image: quay.io/eduk8s/jdk11-environment:200511.a963b67
  session:
    budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
        plugins:
          enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
